### ISSUE TITLE
Can't really build in jungle tiles and forest

### ISSUE THREAD

**Issue by Rivirt** [Sullien/The-Star-Wars#3]
When I'm playing this mod some of the resources go to a jungle tile and and I can't build in jungle tiles any good way to fix this issue?I dunno about forest tiles but real issue is jungle.just found out that you can't build in forest too

**Comment by Rivirt** [comment]
This error message
Shelter has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Extractor has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Trade Point has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Laboratory has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Command Center has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Factory has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Radar Dish has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Power Core has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Force Temple has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Outpost has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Shield Generator has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Military Base has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Mech Complex has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
War Center has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Spaceport has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Road has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Railroad has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Ancient ruins has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
City ruins has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
City center has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Barbarian encampment has an empty `terrainsCanBeBuiltOn`, isn't allowed to only improve resources and isn't unbuildable! Support for this will soon end. Either give this the unique "Unbuildable", "Can only be built to improve a resource" or add "Land", "Water" or any other value to `terrainsCanBeBuiltOn`.
Hero's unique "Great Person" looks like it may be a misspelling of:
	"Great Person - [comment]"
Hero's unique "Great Person" looks like it may be a misspelling of:
	"Great Person - [comment]"

**Comment by Sullien** [comment]
Hello, Thanks for the feedback. I updated it and everything should be working now.

**Comment by Rivirt** [comment]
![Screenshot_2022-05-22-15-07-29-80](https://user-images.githubusercontent.com/105541898/169683326-bde4e868-fe94-4d9f-b06d-f4470051ae8d.png)
Still can't did you add a way to remove obstacles

**Comment by Sullien** [comment]
Yes. The ones that remove Forests and their equivalents are Droids. Odd though if you can't build over forests, I'l update the improvements once more as the new update works slightly different.

**Comment by Sullien** [comment]
Should be working by now

**Comment by Rivirt** [comment]
Closing this now I uninstalled unciv and installed it again download the mod again and now it works thank you for your hard work
